### PR TITLE
Pass options to underlying `spawn()`

### PR DESCRIPTION
**Pull request by ktilcu**
Simple addition to a nice function. ;)

### CODE REVIEW

**Comment by raineorshine** [comment]
Added in cf53c7b

**Comment by ktilcu** [comment]
Awww. Wish i could have made those changes. Had that PR up for a long time. Glad it's done though!

**Comment by raineorshine** [comment]
I actually made the change within a week of your PR 😅. Not sure how I missed it! Just noticed it as I was upgrading dependencies and adding types today.

**Comment by ktilcu** [comment]
Lol. Sounds good! Thanks for circling back around!

**Pull request closed without merging**
